import React, { ReactNode } from 'react';
import Head from 'next/head';

type BasicLayoutProps = {
  children: ReactNode;
};

const BasicLayout = ({ children }: BasicLayoutProps) => {
  return (
    <>
      <Head>
        <title>Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{children}</main>
    </>
  );
};

export default BasicLayout;
