import Head from 'next/head';

import Header from '@/components/Header';
import Nav from '@/components/Nav';
import About from '@/components/About';
import Services from '@/components/Services';
import Work from '@/components/Work';
import Contact from '@/components/Contact';
import Banner from '@/components/Banner';

const Home = () => {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <div className='bg-site bg-no-repeat bg-cover overflow-hidden'>
          <Header />
          <Banner />
          <Nav />
          <About />
          <Services />
          <Work />
          <Contact />
        </div>
      </main>
    </>
  );
};

export default Home;
